//List of files which are indexed.
fl = new Array();
fl["0"]= "Menu2.html";
fl["1"]= "Mainmenu.html";
fl["2"]= "FAQ.html";
fl["3"]= "ch01s02.html";
fl["4"]= "Overview.html";
fl["5"]= "Create.Graph.html";
fl["6"]= "ch03s05.html";
fl["7"]= "Create.Heatmap.html";
fl["8"]= "ch03s04.html";
fl["9"]= "ch01s03.html";
fl["10"]= "ch03s03.html";
fl["11"]= "UserInterface.html";
fl["12"]= "index.html";
fl["13"]= "Create.CSV.html";
fl["14"]= "ch03s07.html";
fl["15"]= "Problemlösung.html";
fl["16"]= "ch01s01.html";
fl["17"]= "Introduction.html";
fl["18"]= "Instructions.html";
var doStem = true