//List of files which are indexed.
fl = new Array();
fl["0"]= "uninstall.html";
fl["1"]= "Menu2.html";
fl["2"]= "Mainmenu.html";
fl["3"]= "FAQ.html";
fl["4"]= "requirements.html";
fl["5"]= "Overview.html";
fl["6"]= "insert.data.html";
fl["7"]= "Create.Graph.html";
fl["8"]= "backup.html";
fl["9"]= "Create.Heatmap.html";
fl["10"]= "about.help.html";
fl["11"]= "about.websense.html";
fl["12"]= "UserInterface.html";
fl["13"]= "index.html";
fl["14"]= "Troubleshooting.html";
fl["15"]= "Create.CSV.html";
fl["16"]= "delete.data.html";
fl["17"]= "Introduction.html";
fl["18"]= "Instructions.html";
var doStem = true